language: ruby
rvm: 2.4.3
services: postgresql
bundler_args: "--without development --deployment -j4"
cache: bundler
before_script:
  - cp config/database.travis.yml config/database.yml
  - bin/rails db:setup
script: bundle exec rspec
