language: ruby
rvm: 2.4.3
addons:
  postgresql: "9.6"
bundler_args: "--without development --deployment -j4"
cache: bundler
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rails db:setup
script: bundle exec rspec
